# Site settings
name: Aastha Rajput
title: Aastha Rajput | Software Engineer
description: Software engineer focused passionate about web development
url: https://aastharajput06.github.io
baseurl: ''
email: aastharajput066@gmail.com
cover: https://aastharajput06.github.io/img/og.png
logo: https://aastharajput06.github.io/img/emojis/technologist.png  
resume: https://aastharajput06.github.io/resume.pdf
social:
  - title: email
    url: mailto:aastharajput066@gmail.com
  # - title: twitter
  #   url: https://twitter.com/aastha06
  # - title: instagram
  #   url: https://instagram.com/rajputain
  - title: codepen
    # url: http://codepen.io/aastharajput
  - title: github
    url: https://github.com/aastharajput06
  - title: linkedin
    url: https://www.linkedin.com/in/aastharajput06/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
