# Site settings
name: Aastha Rajput
title: Aastha Rajput | Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://github.com/aastharajput06/aastha-rajput06.github.io
baseurl: ''
email: aastha.rajput@gwmail.gwu.edu
cover: https://github.com/aastharajput06/aastha-rajput06.github.io/img/og.png
logo: https://github.com/aastharajput06/aastha-rajput06.github.io/img/emojis/technologist.png
resume: https://drive.google.com/file/d/1nOPbQ-4HIlZf7w-0LbEaqAMDA6DMY5bK/view
social:
  - title: email
    url: mailto:aastha.rajput@gwmail.gwu.edu
  # - title: twitter
  #   url: https://twitter.com/aastharajput
  # - title: instagram
  #   url: https://instagram.com/rajputain
  - title: codepen
    url: http://codepen.io/aastharajput
  - title: github
    url: https://github.com/aastharajput06
  - title: linkedin
    url: https://www.linkedin.com/in/aastharajput06/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
